"use client";

import { Button } from "@/components/Button";
import type { RecordingState } from "@/components/VoiceControls";
import type { CameraStatus } from "@/components/CameraPreview";

/**
 * The bottom control dock of the interview room. One place for the actions a
 * candidate reaches for mid-answer, ordered by how often they are used: speak,
 * type, submit — then camera and session exit.
 */
export function RoomControls({
  recordingState,
  cameraEnabled,
  cameraStatus,
  isBusy,
  canSubmit,
  onRecord,
  onStopRecording,
  onToggleCamera,
  onFocusText,
  onSubmit,
  confirmExit,
  onRequestExit,
  onCancelExit,
  onConfirmExit,
  isExiting,
  showNextLocked,
}: {
  recordingState: RecordingState;
  cameraEnabled: boolean;
  cameraStatus: CameraStatus;
  isBusy: boolean;
  canSubmit: boolean;
  onRecord: () => void;
  onStopRecording: () => void;
  onToggleCamera: () => void;
  onFocusText: () => void;
  onSubmit: () => void;
  confirmExit: boolean;
  onRequestExit: () => void;
  onCancelExit: () => void;
  onConfirmExit: () => void;
  isExiting: boolean;
  /** True while the next question is generated by the interviewer, not by you. */
  showNextLocked: boolean;
}) {
  return (
    <div className="glass-strong sticky bottom-0 z-30 -mx-4 mt-6 border-t border-line px-4 py-3 sm:-mx-6 sm:px-6 lg:mx-0 lg:rounded-2xl lg:border">
      {confirmExit ? (
        <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
          <p className="text-sm text-ink-soft">
            End this interview now? Answers already given are saved, but the session won&apos;t be
            scored.
          </p>
          <div className="flex gap-2">
            <Button variant="danger" size="sm" onClick={onConfirmExit} isLoading={isExiting}>
              End interview
            </Button>
            <Button variant="ghost" size="sm" onClick={onCancelExit}>
              Keep going
            </Button>
          </div>
        </div>
      ) : (
        <div className="flex flex-col gap-3">
          <div className="flex flex-wrap items-center gap-2">
            {recordingState === "idle" ? (
              <Button variant="secondary" size="sm" onClick={onRecord} disabled={isBusy}>
                <svg
                  aria-hidden="true"
                  width="15"
                  height="15"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="1.8"
                  strokeLinecap="round"
                >
                  <rect x="9" y="3" width="6" height="11" rx="3" />
                  <path d="M5 11a7 7 0 0 0 14 0M12 18v3" />
                </svg>
                Record answer
              </Button>
            ) : recordingState === "recording" ? (
              <Button variant="danger" size="sm" onClick={onStopRecording}>
                <span aria-hidden="true" className="h-2.5 w-2.5 rounded-full bg-danger" />
                Stop recording
              </Button>
            ) : (
              <span className="flex items-center gap-2 rounded-lg border border-line px-3 py-2 text-xs text-ink-soft">
                <span aria-hidden="true" className="h-1.5 w-1.5 animate-pulse-soft rounded-full bg-plum" />
                Transcribing…
              </span>
            )}

            <Button variant="ghost" size="sm" onClick={onFocusText} disabled={isBusy}>
              <svg
                aria-hidden="true"
                width="15"
                height="15"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.8"
                strokeLinecap="round"
              >
                <path d="M4 7h16M4 12h10M4 17h7" />
              </svg>
              Write answer
            </Button>

            <Button
              variant="ghost"
              size="sm"
              onClick={onToggleCamera}
              aria-pressed={cameraEnabled}
            >
              <svg
                aria-hidden="true"
                width="15"
                height="15"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.8"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <path d="M3 8.5A2.5 2.5 0 0 1 5.5 6h6A2.5 2.5 0 0 1 14 8.5v7A2.5 2.5 0 0 1 11.5 18h-6A2.5 2.5 0 0 1 3 15.5v-7Z" />
                <path d="m14 11 5-3v8l-5-3" />
                {!cameraEnabled && <path d="m3 3 18 18" />}
              </svg>
              {cameraEnabled ? "Camera on" : "Camera off"}
              {cameraStatus === "active" && (
                <span aria-hidden="true" className="h-1.5 w-1.5 rounded-full bg-success" />
              )}
            </Button>

            <div className="ms-auto flex items-center gap-2">
              <Button
                size="md"
                onClick={onSubmit}
                disabled={!canSubmit || isBusy}
                isLoading={isBusy}
              >
                Submit answer
              </Button>
              <Button
                variant="ghost"
                size="sm"
                onClick={onRequestExit}
                disabled={isBusy}
                className="hidden sm:inline-flex"
              >
                End interview
              </Button>
            </div>
          </div>

          <p className="text-[11px] leading-5 text-ink-mute">
            {showNextLocked
              ? "Next question unlocks when you submit this answer — the interviewer decides what comes next based on what you say."
              : "Answer with your voice or the text box. Both routes are scored identically."}
          </p>
        </div>
      )}
    </div>
  );
}
